### ISSUE TITLE
Applying trial phases for subscriptions

### ISSUE THREAD

**Issue by gldstrrbt** [RevenueCat/purchases-capacitor#237] opened 2024-04-06 16:44 UTC
I've added a free trial phase to my app's subscriptions in the Google Play Console, but they don't appear to be showing up when I call to list the app's subscription offerings. The values for both freePhase and introPhase are null, and there's nothing else showing up that gives confidence that the trial offer phases will be applied as intended when users pay for their initial subscription. 

Is there any way of getting this information from this plugin? I've looked everywhere on the dashboard side of RevenueCat and can't seem to find anything there.

Any help would be greatly appreciated! Thank you in advance!

**Comment by rglanz-rc** [comment] 2024-04-10 15:54
Hi,

Is the [subscriptionOptions](https://revenuecat.github.io/cordova-plugin-purchases-docs/5.7.4/interfaces/PurchasesStoreProduct.html#subscriptionOptions) null as well? That should contain more info on the [StoreProduct's offers](https://www.revenuecat.com/docs/subscription-guidance/subscription-offers#more-control-over-offer-selection).

**Comment by rglanz-rc** [comment] 2024-04-30 16:21
Closing due to staleness, but lmk if this is ongoing.

**Closed by rglanz-rc** 2024-04-30 16:21 UTC
